### ISSUE TITLE
OData Service for Business Partner is not available in API Business Hub and breaks the tutorial

### ISSUE THREAD

**Issue by WinterMaxNeomatic** [SAP-samples/cloud-sample-spaceflight-java#3]
Alternativ service "Master Data for Business Partner" only returns:
"Master Data for Business Partner API is unavailable".

**Comment by chgeo** [comment]
It's still available: https://api.sap.com/api/API_BUSINESS_PARTNER/overview

**Comment by chgeo** [comment]
Please also check this one: https://api.sap.com/api/SCP_API_BUSINESS_PARTNER/overview
