### ISSUE TITLE
Error in deploy odata-mock-server

### ISSUE THREAD

**Issue by epirovano** [SAP-samples/cloud-sample-spaceflight-java#4]
Hi, 
I'm trying to deploy the odata-mock-server.mtar into the SAP Cloud Platform but I get the following error:

�[31;1m**ERROR**�[0m Unable to install node: no match found for ^8.9.4 in [10.18.0 10.18.1 12.14.0 12.14.1 13.5.0 13.6.0]

**Comment by chgeo** [comment]
Hi,

thanks for reporting.  It seems, CF no longer supports Node.js 8.  Commit be2688e9 fixes the deploy archive to use whatever version CF uses as default.
After pulling the archive from Github again, deployment should work.

Thanks for reporting
Christian
